json.extract! @project,
              :id,
              :title,
              :summary,
              :description,
              :goal_amt,
              :current_amt,
              :start_date,
              :end_date,
              :category_id,
              :creator_id,
              :backings
